# 100道Numpy练习题

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

1. 导入numpy并使用np简称

In [1]:
import numpy as np

2. 查看numpy的版本和配置信息

In [2]:
np.__version__

'1.18.0'

In [3]:
np.__config__

<module 'numpy.__config__' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__config__.py'>

3. 创建一个长度为10，所有元素为0的数组

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. 查看一个数组的内存大小

In [5]:
arr = np.zeros((10, 10))
"arr bytes: {}".format(arr.size * arr.itemsize)

'arr bytes: 800'

5. 获取add的函数说明

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

<font color='orange'>ps：此外我们还可以使用np.add.\__doc\__, help(np.add)获取帮助文档。</font>

6. 创建长度为5，值为0的数组，并将最后一个元素改为1

In [7]:
arr = np.zeros(5)
arr[4] = 1
arr

array([0., 0., 0., 0., 1.])

7. 创建一个值从10-49的数组

In [8]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. 逆序输出一个数组

In [9]:
np.arange(10, 50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

<font color='orange'>ps:这里使用的是python的切片技巧！</font>

9. 创建一个形状为3x3的数组，数值从0-8

In [10]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. 找到数组\[1,2,0,0,4,0\]中非0元素的位置索引

In [11]:
arr = np.array([1,2,0,0,4,0])
np.where(arr!=0)

(array([0, 1, 4]),)

In [12]:
np.nonzero(arr)

(array([0, 1, 4]),)

<font color='orange'>ps:可以看到直接实现的方法是nonzero(), 同样的where函数也能实现！</font>

11. 创建一个 3x3 的单位矩阵

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. 创建一个 3x3x3的随机数组

In [15]:
np.random.random((3, 3, 3))

array([[[0.68080353, 0.30468174, 0.58815186],
        [0.79429947, 0.20927007, 0.38909384],
        [0.7458939 , 0.26689184, 0.55952418]],

       [[0.18800697, 0.57480648, 0.90139493],
        [0.16965376, 0.28047126, 0.12236697],
        [0.76011872, 0.51729075, 0.00843112]],

       [[0.0136452 , 0.700653  , 0.57864371],
        [0.34266952, 0.70591975, 0.95060711],
        [0.01260495, 0.99651854, 0.70602901]]])

13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [16]:
arr = np.random.random((10, 10))
np.max(arr), np.min(arr)

(0.9977927114642973, 0.005030590448130257)

14. 创建一个长度为30的随机向量并找到它的平均值

In [17]:
arr = np.random.random(30)
np.mean(arr)

0.5370287661727189

15. 创建一个二维数组，其中边界值为1，其余值为0

In [18]:
arr = np.zeros((5, 5))
arr[[0, -1], :] = 1
arr[:, [0, -1]] = 1
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

<font color='orange'>ps:这里主要使用的是花哨索引和切片来实现的！</font>

16. 对于一个存在在数组，如何添加一个用0填充的边界?

In [20]:
arr = np.arange(16).reshape(4, 4)
np.pad(arr, pad_width=1, mode='constant', constant_values=0)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  0],
       [ 0,  4,  5,  6,  7,  0],
       [ 0,  8,  9, 10, 11,  0],
       [ 0, 12, 13, 14, 15,  0],
       [ 0,  0,  0,  0,  0,  0]])

17. 以下表达式运行的结果分别是什么? <br>
nan, inf 的计算规则：

In [21]:
0 * np.nan

nan

In [22]:
np.nan == np.nan

False

In [23]:
np.inf > np.nan

False

In [24]:
np.nan - np.nan

nan

In [25]:
0.3 == 0.1 * 3

False

18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [26]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [29]:
arr = np.zeros((8, 8))
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [1]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [4]:
np.tile([[0, 1], [1, 0]], (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

22. 对一个5x5的随机矩阵做归一化

In [11]:
arr = np.arange(1, 26).reshape(5, 5)
arr_min, arr_max = arr.min(), arr.max()
(arr - arr_min) / (arr_max - arr_min)

array([[0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667],
       [0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ],
       [0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333],
       [0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667],
       [0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ]])

23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [3]:
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.float)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', '<f8')])

In [4]:
arr = np.array([(23, 45, 66, 0.4), (24, 56, -56, 0.8)], dtype=color)
arr[1], arr[0]['r']

((24, 56, 200, 0.8), 23)

In [5]:
len(arr)

2

可以看到每个元组被处理成一个数据，注意无符号的负数溢出成了200。更多的内容大家可以自己尝试，这里给出的是自己定义颜色数据类型！

24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [6]:
np.dot(np.ones((5, 3)), np.ones((3, 2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

这里实现的是矩阵的点积，得到5x2的矩阵。

25. 给定一个一维数组，对其在3到8之间的所有元素取反。

In [11]:
arr = np.arange(11)
arr[(arr>=3) & (arr<=8)] = -arr[(arr>=3) & (arr<=8)]
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

个人更喜欢`np.where()`实现：

In [14]:
arr = np.arange(11)
np.where((arr>=3) & (arr<=8), -arr, arr)

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

26. 下面运行后的结果是什么?

In [31]:
sum(range(5), -1)

9

In [33]:
np.sum(range(5), -1)

10

其实在这里我们应该去关注参数，两个`sum()`的参数意义是不一样的：<br>
第一个-1是start的含义，从start开始再求和。等价sum+start<br>
第二个-1是axis的含义，维度。-1等价0，行整体求和。

27. 考虑一个整数向量Z,下列表达合法的是哪个?

    + Z**Z
    + 2 << Z >> 2
    + Z <- Z 
    + 1j*Z 
    + Z/1/1 
    + Z<Z\>Z

In [3]:
Z = np.arange(5)
Z

array([0, 1, 2, 3, 4])

In [4]:
Z**Z # 表示每个元素指数广播

array([  1,   1,   4,  27, 256])

In [7]:
2 << Z >> 2

array([0, 1, 2, 4, 8])

In [9]:
for item in Z:
    res = 2 << item  # 左移
    print(res >> 2)  # 右移

0
1
2
4
8


In [10]:
Z < -Z # Z的所有元素为正数，得到的结果全为false

array([False, False, False, False, False])

In [11]:
1j * Z # 所有的元素乘以虚数

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [12]:
Z / 1 / 1 # 每个元素连除两个1，注意得到的是浮点型数据

array([0., 1., 2., 3., 4.])

In [13]:
Z < Z > Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

判断符号的连续作用在ndarray中是不能使用的，代替方案是：

In [14]:
(Z < Z) & (Z > Z) # 很明显不存在这样的元素

array([False, False, False, False, False])

28. 下列表达式的结果分别是什么?
    + np.array(0) / np.array(0)
    + np.array(0) // np.array(0)
    + np.array([np.nan]).astype(int).astype(float)

In [15]:
np.array(0) / np.array(0)

<ipython-input-15-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [16]:
np.array(0) // np.array(0)

<ipython-input-16-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [23]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

前两个计算将0作为分母导致计算结果nan，0的同时带来了warning。<br>
nan在numpy中默认是浮点类型，在进行int类型强制转化的时候数据发生不可预期的情况！

29. 如何从零位对浮点数组做舍入 ?

In [29]:
arr = np.random.uniform(-10, 10, 10)
print(arr)
print(np.copysign(np.ceil(np.abs(arr)), arr))
print(np.round(arr, 0))

[-1.42416575 -2.48860138 -6.20699751  8.83557465  7.31806015  9.75641509
  1.59322946 -3.8838304   0.63170392  7.79687834]
[-2. -3. -7.  9.  8. 10.  2. -4.  1.  8.]
[-1. -2. -6.  9.  7. 10.  2. -4.  1.  8.]


30. 如何找到两个数组中的共同元素?

In [30]:
np.random.seed(0)
arr1 = np.random.randint(0, 10, 10)
arr2 = np.random.randint(0, 10, 10)
arr1, arr2

(array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4]), array([7, 6, 8, 8, 1, 6, 7, 7, 8, 1]))

In [31]:
np.intersect1d(arr1, arr2)

array([7])

`np.intersect1d()`函数给出了解决方案，找出数组中的共同元素(交集)。<br>
`np.union1d()`并集。<br>
`np.setdiff1d()`差集。<br>
`np.setxor1d()`对称差。

31. 如何忽略numpy的警告<font color='red'>(不建议这么做)</font>？

In [2]:
np.zeros(1) / 0

<ipython-input-2-5beb98ad7c80>:1: RuntimeWarning: invalid value encountered in true_divide
  np.zeros(1) / 0


array([nan])

In [3]:
default = np.seterr(all='ignore') # 忽略所有的警告信息
np.zeros(1) / 0  

array([nan])

In [ ]:
_ = np.seterr(**default)  # 恢复所有的警告信息

In [6]:
np.zeros(1) / 0

array([nan])